# Compile options
BUILD_EXTRA_FLAGS += -DDEBUG
#BUILD_EXTRA_FLAGS += -DMUTILA_DEBUG
#BUILD_EXTRA_FLAGS += -DDEBUG_OUTPUT=Serial

# Supported speeds: 921600 460800 230400 115200 57600 9600
UPLOAD_SPEED = 921600

# Set for your hardware
# For NodeMCU (ESP8266):
BOARD = nodemcu

# For Node32-S (ESP32):
#CHIP = esp32
#BOARD = node32s

include ../esp.mk

